### ISSUE TITLE
Gallery Issue

### ISSUE THREAD

**Issue by ashwin3082002** [thecoding-society/website#5]
The page is taking time to load due to heavy images in the website's gallery section of the website, Optimize the website performance and find out another way to add gallery without compromising on the performance of the website. 

Assigned this issue to @aviiciii

**Comment by aviiciii** [comment]
Hey @ashwin3082002, due to access issues in Onedrive I switched the image storage to Imagekit.io, tested the site and the website is live without issues. 

I am looking to further improve the responsiveness of the page. I will notify you on solution for the matter. Let the issue remain open and I will follow up.

**Comment by ashwin3082002** [comment]
Noted

**Comment by ashwin3082002** [comment]
@aviiciii Closing this issue, Thanks for your contribution.

**Comment by ashwin3082002** [comment]
@aviiciii The main logo of the website in the index page is missing, Kindly look into it...

**Comment by aviiciii** [comment]
@ashwin3082002 Thank you for noting them. I have fixed the image urls now and the website seems to be working as expected.
